name: Build and Deploy

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Шаг 1: Клонировать репозиторий
      - name: Checkout repository
        uses: actions/checkout@v2

      # Шаг 2: Установить Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22' 

      # Шаг 3: Установить зависимости
      - name: Install dependencies
        run: npm install

      # Шаг 4: Собрать проект с помощью Webpack
      - name: Build with Webpack
        run: npm run build

      # Шаг 5: Установить деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.GITHUB_TOKEN }}  # Используется токен для доступа
          publish_dir: ./dist  # Путь к каталогу с скомпилированными файлами 